name: Build

run-name: Build for ${{ github.ref_name }}

concurrency:
  group: build-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_call:
    outputs:
      artifact_name:
        description: Name of the artifact uploaded in GitHub containing the built DLLs
        value: ${{ jobs.build.outputs.artifact_name }}

env:
  BIN_FOLDER: '**/bin/Release/**'
  OBJ_FOLDER: '**/obj/Release/**'

  ARTIFACT_NAME: CleanShortener

jobs:
  build:
    runs-on: windows-latest
    outputs:
      artifact_name: ${{ env.ARTIFACT_NAME }}

    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache-dependency-path: '**/packages.lock.json'
          cache: true

      - name: Restore Dependencies
        run: dotnet restore --locked-mode

      - name: Build Solution
        run: |
          dotnet build CleanShortener.sln `
          -c Release `
          --no-restore

      - name: Debug Directory
        run: Tree

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: |
            ${{ env.BIN_FOLDER }}
            ${{ env.OBJ_FOLDER }}