name: Unit Tests

run-name: Unit Tests for ${{ github.ref_name }}

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main

  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  test:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.publish_folder }}

      - name: Run Unit Tests
        run: |
          dotnet test CleanShortener.Tests\CleanShortener.Tests.csproj `
          --filter "FullyQualifiedName!~ArchitecturalTests" `
          --no-build `
          --configuration Release `
          --logger:"console;verbosity=detailed" `
          --logger:"html;logfilename=testResults.html"

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: testResults
          path: CleanShortener.Tests\TestResults\testResults.html